# Generated by Django 2.2.17 on 2021-01-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20210119_1535"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="correct",
            new_name="answers",
        ),
    ]
